# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 75c4608d-6457-599e-a6c7-c4365bc04454

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: https://auragpttest.azurecr.io/
        username: auragpttest
        password: AQVnnWDmh9xSShJKbSzNDamrPDYE62Zrqg+eBX1EPm+ACRBQHzzt

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: auragpttest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3037e2558b3f4cb7bff2706f98c19d71 }}/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '75c4608d-6457-599e-a6c7-c4365bc04454'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_584ffd0a3bc44d58840a461e3f84fadd }}
        images: 'auragpttest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3037e2558b3f4cb7bff2706f98c19d71 }}/sample-app-aoai-chatgpt:${{ github.sha }}'
